(function attachAppConfig(globalScope) {
  const BOARD_NEWS_IMAGE_RECT = { x: 164, y: 276, width: 696, height: 937 };

  const config = {
    monitoringProviders: [
      { id: 'x', title: 'X', mode: 'account', hint: 'Добавьте @аккаунт или ссылку на профиль.' },
      { id: 'reddit', title: 'Reddit', mode: 'account', hint: 'Добавьте сабреддит или профиль, например r/cryptocurrency.' },
      { id: 'telegram', title: 'Telegram', mode: 'account', hint: 'Добавьте @канал или invite-ссылку.' },
      { id: 'instagram', title: 'Instagram', mode: 'account', hint: 'Добавьте @аккаунт источника.' },
      { id: 'reuters', title: 'Reuters', mode: 'account', hint: 'Добавьте профиль, ленту или раздел редакции.' },
      { id: 'bloomberg', title: 'Bloomberg', mode: 'account', hint: 'Добавьте автора, раздел или профиль.' },
      { id: 'coindesk', title: 'CoinDesk', mode: 'account', hint: 'Добавьте рубрику или страницу автора.' },
      { id: 'grok', title: 'Grok', mode: 'prompt', hint: 'Введите промпт для поиска новостей через Grok.' },
      { id: 'gemini', title: 'Gemini', mode: 'prompt', hint: 'Введите промпт для поиска новостей через Gemini.' },
    ],
    boardNewsImageRect: BOARD_NEWS_IMAGE_RECT,
    boardSlotConfig: {
      '1080x1920': {
        asset: { width: 1024, height: 1536 },
        imageRect: BOARD_NEWS_IMAGE_RECT,
        width: BOARD_NEWS_IMAGE_RECT.width,
        height: BOARD_NEWS_IMAGE_RECT.height,
        title: { top: '34%', left: '51%', width: '36%', size: '40px' },
      },
      '1920x1080': {
        asset: { width: 1536, height: 1024 },
        imageRect: {
          x: Math.round((BOARD_NEWS_IMAGE_RECT.x / 1024) * 1536),
          y: Math.round((BOARD_NEWS_IMAGE_RECT.y / 1536) * 1024),
          width: Math.round((BOARD_NEWS_IMAGE_RECT.width / 1024) * 1536),
          height: Math.round((BOARD_NEWS_IMAGE_RECT.height / 1536) * 1024),
        },
        width: Math.round((BOARD_NEWS_IMAGE_RECT.width / 1024) * 1536),
        height: Math.round((BOARD_NEWS_IMAGE_RECT.height / 1536) * 1024),
        title: { top: '34%', left: '51%', width: '36%', size: '40px' },
      },
    },
    defaultNewsSceneSettings: {
      fitMode: 'cover',
      imageAlign: 'center',
      offsetX: 0,
      offsetY: 0,
      zoom: 100,
      imageX: 16,
      imageY: 18,
      imageWidth: 68,
      imageHeight: 61,
      titleX: 51,
      titleY: 34,
      titleWidth: 36,
      titleSize: 40,
    },
    commandHelpItems: [
      ['*speak_pause 100', 'Пауза в речи на 100 мс.'],
      ['*left_arm_low', 'Поднять левую руку немного (ассеты позже).'],
      ['*left_arm_mid', 'Поднять левую руку средне (ассеты позже).'],
      ['*left_arm_high', 'Поднять левую руку выше (ассеты позже).'],
      ['*left_arm_down', 'Опустить левую руку на стол (ассеты позже).'],
      ['*right_arm_low', 'Поднять правую руку немного (ассеты позже).'],
      ['*right_arm_mid', 'Поднять правую руку средне (ассеты позже).'],
      ['*right_arm_high', 'Поднять правую руку выше (ассеты позже).'],
      ['*right_arm_down', 'Опустить правую руку на стол (ассеты позже).'],
      ['*take_sheet', 'Взять листок (ассеты позже).'],
      ['*read_sheet', 'Читать листок (ассеты позже).'],
      ['*down_sheet', 'Положить листок на стол (ассеты позже).'],
      ['*left_turn_head_low', 'Поворот головы влево немного (ассеты позже).'],
      ['*left_turn_head_mid', 'Поворот головы влево средне (ассеты позже).'],
      ['*left_turn_head_high', 'Поворот головы влево сильно (ассеты позже).'],
      ['*right_turn_head_low', 'Поворот головы вправо немного (ассеты позже).'],
      ['*right_turn_head_mid', 'Поворот головы вправо средне (ассеты позже).'],
      ['*right_turn_head_high', 'Поворот головы вправо сильно (ассеты позже).'],
      ['*left_tilt_head_low', 'Наклон головы влево немного (ассеты позже).'],
      ['*left_tilt_head_mid', 'Наклон головы влево средне (ассеты позже).'],
      ['*left_tilt_head_high', 'Наклон головы влево сильно (ассеты позже).'],
      ['*right_tilt_head_low', 'Наклон головы вправо немного (ассеты позже).'],
      ['*right_tilt_head_mid', 'Наклон головы вправо средне (ассеты позже).'],
      ['*right_tilt_head_high', 'Наклон головы вправо сильно (ассеты позже).'],
      ['*emotion_smile', 'Эмоция улыбка (ассеты позже).'],
      ['*emotion_surprise', 'Эмоция удивление (ассеты позже).'],
      ['*emotion_doubt', 'Эмоция сомнение (ассеты позже).'],
      ['*board_news_front 0', 'Перенести слой изображения новости впереди всех остальных слоев, 0 = без ограничения по времени.'],
      ['*board_news_back 0', 'Перенести доску с новостью назад, 0 = базовое состояние.'],
    ],
    rubricCatalog: [
      { type: 'ursas_index', title: 'Ursas Index' },
      { type: 'number_of_day', title: 'Number of the day' },
      { type: 'top_10_coins_gainers', title: 'Top 10 coins gainers' },
      { type: 'top_10_coins_losers', title: 'Top 10 coins losers' },
      { type: 'top_10_stocks', title: 'Top 10 stocks movers' },
      { type: 'crypto_bubbles', title: 'Crypto bubbles' },
      { type: 'bear_world_news', title: 'Bear-world news' },
      { type: 'bear_language', title: 'Язык медведей' },
      { type: 'roadmap_news', title: 'Roadmap news' },
      { type: 'ursass_tube_leaderboard', title: 'Ursass Tube leaderboard' },
    ],
    mouthSprites: {
      idle: {
        path: 'public/mounth/mounth_close_neitral.webp',
        frames: 10,
        scale: 0.6,
        offset_x: 20,
        offset_y: -12,
      },
      closed: {
        path: 'public/mounth/mounth_close_neitral.webp',
        frames: 10,
        scale: 0.6,
        offset_x: 20,
        offset_y: -12,
      },
      open: {
        path: 'public/mounth/mounth_open_beauty.webp',
        variants: [
          'public/mounth/mounth_open_beauty.webp',
          'public/mounth/mounth_open_round.webp',
          'public/mounth/mounth_open_trapecia.webp',
        ],
        frames: 8,
        scale: 0.6,
        offset_x: 20,
        offset_y: -14,
      },
    },
  };

  globalScope.UrsasAppConfig = config;
})(window);
